$("document").ready(function(){
    $(".desn").click(function(){
        $("#des-image").toggle();
        $(".lion").toggle();
    })
})
$("document").ready(funtion(),{
    $(".desn-2").click(function(){
        $("#des-image-2").toggle();
        $(".dev").toggle();
    })
})
